server:
  port: 3100

spring:
  application:
    name: config-server
  config:
    import: optional:file:.env

  profiles:
    active: native, git

  cloud:
    config:
      server:
        native:
          search-locations: ${LOCAL_PATH}
        git:
          uri: https://github.com/PokeHerb/pokeherb
          default-label: main
          search-paths: configs/**
          basedir: configs
          clone-on-start: true