server:
  port: 3100

spring:
  application:
    name: config-server
  config:
    import: optional:file:.env

  profiles:
    active: native, git

  cloud:
    config:
      server:
        native:
          search-locations: ${LOCAL_PATH}
        git:
          uri: https://github.com/PokeHerb/pokeherb
          default-label: main
          search-paths:
            - configs
            - configs/*
          basedir: configs
          clone-on-start: true

eureka:
  instance:
    prefer-ip-address: false
    hostname: localhost

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:3150/eureka/