server:
  port: 3100

spring:
  application:
    name: config-server

  profiles:
    active: native, git

  cloud:
    config:
      server:
        native:
          search-locations: 'file:///Users/yejin/Documents/herb/project-config'
        git:
          uri: https://github.com/PokeHerb/pokeherb
          default-label: main
          search-paths: configs/**
          basedir: configs
          clone-on-start: true